pepew/urls.py
from django.contrib import admin
from django.urls import path

from pages.views import *

urlpatterns = [
    path('home/', home_view, name='home'),
    path('', home2_view, name='home2'),
    path('portfolio/', portfolio_view, name="portfolio"),
    path('programming/', programming_view, name="programming"),
    path('photography/', photography_view, name="photography"),
    path('profile/', profile_view, name="profile"),
    path('matkulCreate/', matkul_form_create, name="matkul_form_create"),
    path('matkulList/', matkul_list_view, name="matkul_list_view"),
    path('matkulDelete/<str:pk>/', matkul_delete_view, name="matkul_delete"),
    path('matkulDetail/<str:pk>/', matkul_detail_view, name="matkul_detail_view"),
    path('kegiatanList/', kegiatan_list_view, name="kegiatan_list_view"),
    path('kegiatanAdd/', kegiatan_add_view, name="kegiatan_add_view"),
    path('kegiatanDelete/<str:pk>/', kegiatan_delete_view, name="kegiatan_delete_view"),
    path('orangDelete/<str:pk>/', orang_delete_view, name="orang_delete_view"),
    path('booksSearch/', books_search, name="books_search"),
    path('login/', login_view, name="login"),
    path('signup/', signup_view, name="signup"),
    path('logout/', logout_view, name="logout"),
    path('testpage/', testpage_view, name="testpage"),
    path('admin/', admin.site.urls),
]

pages/models.py
from django.db import models
from django.core.validators import *

#CHOICES
CHOICES = (
    ("GSL1920", "Gasal 2019/2020"),
    ("GNP1920", "Genap 2019/2020"),
    ("GSL2021", "Gasal 2020/2021"),
    ("GNP2021", "Genap 2020/2021"),
    ("GSL2122", "Gasal 2021/2022"),
    ("GNP2122", "Genap 2021/2022"),
    ("GSL2223", "Gasal 2022/2023"),
    ("GNP2223", "Genap 2022/2023"),
)
# Create your models here.
class Matkul(models.Model):

    namaMatkul = models.CharField(max_length = 100)
    dosenPengajar = models.CharField(max_length = 100)
    jumlahSKS = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(24)])
    deskripsi = models.CharField(max_length = 1000)
    semester = models.CharField(max_length = 10, choices=CHOICES)
    ruangKelas = models.CharField(max_length = 100)
    #semester = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(8)])
    
    def __str__(self):
        return self.namaMatkul

class Kegiatan(models.Model):
    
    namaKegiatan = models.CharField(max_length = 100)

    def __str__(self):
        return self.namaKegiatan

class Orang(models.Model):

    kegiatanOrang = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null=True)
    namaOrang = models.CharField(max_length = 100)

    def __str__(self):
        return self.namaOrang

pages/templates/books_search.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Books</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <h2 class="is-size-3 has-text-centered mb-6"><strong>Book Search</strong></h2>
      <input class = "input mb-4" id = "keyword_buku" placeholder="Insert Book Title Here...">
      <button class="button is-black" id="button">Submit</button>

      <div class="book_box_container">

      </div>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Homepage</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <p class="m-6 p-6">
        <h1 class="title has-text-centered">
          Hi! Welcome to my website!
        </h1>
        <p class="subtitle has-text-centered">
          Click one of these to get started!
        </p>
      </p>
      <p class="m-6 p-6 has-text-centered">
        <a class="button is-outlined is-large" href="{% url 'profile' %}">
          Profile
        </a>
        <a class="button is-outlined is-large" href="{% url 'portfolio' %}">
          Portfolio
        </a>
      </p>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/index.html
{% load static %}

<HTML>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <body>
        <h1>Profil Diri</h1>
        <img img src="{% static 'pepew/images/IMG_1285_Crop.jpg' %}", height="100", width="100">
        <br>
        Nama: Adam Syauqi
        <br>
        NPM: 1906292881
        <br>
        Angkatan: 2019
        <br>
        Tempat Kuliah: Universitas Indonesia
        <br>
        Hobi: Gacha
        <br>
        Deskripsi Tentang Saya: A hardworker, persistent, consistent, photography and music enthusiast, game and cat lover who studies at Computer Science Universitas Indonesia Class of 2019
        <br>
        <br>
        <table><caption>Riwayat Pendidikan</caption>
            <thead>
                <tr>
                    <th>Sekolah</th>
                    <th>Tahun</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>TK Al-Ikhsan</td>
                    <td>2004-2008</td>
                </tr>
                <tr>
                    <td>SDI Tugasku</td>
                    <td>2008-2013</td>
                </tr>
                <tr>
                    <td>SMP Labschool Jakarta</td>
                    <td>2013-2016</td>
                </tr>
                <tr>
                    <td>SMA Labschool Jakarta</td>
                    <td>2016-2019</td>
                </tr>
                <tr>
                    <td>Universitas Indonesia</td>
                    <td>2019-Sekarang</td>
                </tr>
            </tbody>
        </table>
        <a href="https://www.instagram.com/adamsyauqi/">
            <img src="{% static 'pepew/images/instagram-logo-png-2426.png' %}", height="50", width="50">
         </a>
    </body>
</HTML>

pages/templates/kegiatan_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Activity List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/18744820a2.js" crossorigin="anonymous"></script>
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <h1 class="has-text-weight-bold has-text-centered is-size-4">Activities List</h1>
      <br>
        <form action="/kegiatanAdd/", method="POST">
          {% csrf_token %}
          {{ form_kegiatan }}
          <button class="button is-success is-fullwidth" type="submit">Add Activity</button>
          <br>
          <br>
        </form>       
        {% for kegiatan in kegiatan_list %}
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <p>
                  {{ kegiatan.namaKegiatan }}
                  <br>
                  {% for orang in kegiatan.orang_set.all %}
                  <div class="field">
                    <div class="control">
                      <form action="/orangDelete/{{ orang.id }}/", method="POST">
                        {{ orang.namaOrang }}
                        {% csrf_token %}
                      <button type="submit" class="button is-small is-danger"><i class="fas fa-trash-alt"></i></button>
                      </form>
                    </div>
                  </div>
                  {% endfor %}
                  <p>Add Your Name Here</p>
                  <div class="field has-addons">
                    <div class="control">
                      <form method="POST" action="">
                        <input type="hidden" name="kegiatanOrang" value="{{ kegiatan.id }}">
                        {{ form_orang.namaOrang }}
                        {% csrf_token %}
                        </div>   
                        <div class="control">
                          <button class="button is-success" type="submit">Join Activity</button>
                        </div>
                      </form>
                  </div>
                  <div class="field">
                    <form action="/kegiatanDelete/{{ kegiatan.id }}/", method="POST">
                      {% csrf_token %}
                      <button type="submit" class="button is-danger"><i class="fas fa-trash-alt"></i><p>Delete Activity</p></button>
                    </form>
                  </div>
                </p>
              </div>
            </div>
          </article>
        </div>
      {% endfor %}
      </div>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  {% extends 'navbarFooter.html' %}
  {% load static %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <div class="card has-background-dark">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4 has-text-white">Login</p>
              <p class="subtitle is-6 has-text-white">Please enter your username and password</p>
            </div>
          </div>
          <div class="content">
            <form method="POST" action="">
              {% csrf_token %}
              <div class="field">
                <p class="control has-icons-left">
                  <input class="input" type="text" name="username">
                  <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </p>
              </div>
              <div class="field">
                <p class="control has-icons-left">
                  <input class="input" type="password" name="password">
                  <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </p>
              </div>
              <input class="button is-white" type="submit" value="Login">
            </form>
            <br>
          {% for message in messages %}
            <p>{{message}}</p>
          {% endfor %}
          <p class="has-text-white">Don't have an account? Register here!</p>
          <a class="button is-link" href="{% url 'signup' %}"><p>Signup</p></a>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
  {% endblock %}
</html>

pages/templates/matkul_create_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Course</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <div class="field">
        <form method="POST">
        {% csrf_token %}
        <label class="label">Course Name</label>
        <div class="control py-3">{{ form.namaMatkul }}</div>
        <label class="label">Lecturer's Name</label>
        <div class="control py-3">{{ form.dosenPengajar }}</div>
        <label class="label">Credit Score</label>
        <div class="control py-3">{{ form.jumlahSKS }}</div>
        <label class="label">Description</label>
        <div class="control py-3">{{ form.deskripsi }}</div>
        <label class="label">Term</label>
        <div class="select my-3">{{ form.semester }}</div>
        <label class="label">Course Room</label>
        <div class="control py-3">{{ form.ruangKelas }}</div>
        <div class="control py-3"><input class="button is-success" type='submit' value="Save" /></div>
      </form>
    </div>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/matkul_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Delete Course</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  {% load static %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
        <p class="is-size-5 py-3">Are you sure you want to delete "{{item}}"?</p>
        <form action="{% url 'matkul_delete' item.id %}" method="POST">
            {% csrf_token %}
          <a class="button is-danger" href="{% url 'matkul_list_view' %}">Cancel</a>
          <input class="button is-link" type='submit' value="Confirm" />

        </form>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/matkul_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Course</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
    {% load static %}
  <section class="section">
    <div class="container">
      <h1 class="title py-2">Course Name</h1>
      <p class="subtitle">{{ matkul_detail.namaMatkul }}</p>
      <h1 class="title py-2">Lecturer</h1>
      <p class="subtitle">{{ matkul_detail.dosenPengajar }}</p>
      <h1 class="title py-2">Credit Score</h1>
      <p class="subtitle">{{ matkul_detail.jumlahSKS }}</p>
      <h1 class="title py-2">Description</h1>
      <p class="subtitle">{{ matkul_detail.deskripsi }}</p>
      <h1 class="title py-2">Term</h1>
      <p class="subtitle">{{ matkul_detail.semester }}</p>
      <h1 class="title py-2">Course Room</h1>
      <p class="subtitle">{{ matkul_detail.ruangKelas }}</p>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/matkul_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Courses List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <div class="table-container">
        <table class="table is-fullwidth"><caption><h1 class="has-text-weight-bold">Courses List</h1></caption>
            <thead>
                <tr>
                    <th>Course Name</th>
                    <th>Lecturer</th>
                    <th>Credit Score</th>
                    <th>Description</th>
                    <th>Term</th>
                    <th>Course Room</th>
                    <th>Delete Button</th>
                    <th>Details</th>
                </tr>
            </thead>
            <tbody>
                {% for matkul in object_list %}
                <tr>
                    <td>{{ matkul.namaMatkul }}</td>
                    <td>{{ matkul.dosenPengajar }}</td>
                    <td>{{ matkul.jumlahSKS }}</td>
                    <td>See in Details</td>
                    <td>{{ matkul.semester }}</td>
                    <td>{{ matkul.ruangKelas }}</td>
                    <td><a class="button is-danger is-small" href="{% url 'matkul_delete' matkul.id %}">Delete</a></td>
                    <td><a class="button is-info is-small" href="{% url 'matkul_detail_view' matkul.id %}">Details</a></td>
                </tr>
            </tbody>
        {% endfor %}
        </table>
      </div>
      <a class="button is-success is-fullwidth" href="{% url 'matkul_form_create' %}">Add Course</a>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/navbarFooter.html
{% load static %}

<body>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="true" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
        </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item is-size-5" href="/">
                <p class="">Home</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'books_search' %}">
                <p class="">Books</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'kegiatan_list_view' %}">
                <p class="">Activities</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'matkul_list_view' %}">
                <p class="">Courses</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'profile' %}">
                <p class="">Profile</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'portfolio' %}">
                <p class="">Portfolio</p>
            </a>
        </div>
        <div class="navbar-end">

            {% if request.user.is_anonymous %}
            <a class="navbar-item is-size-5" href="{% url 'login' %}">
                <p class="">Login</p>
            </a>
            <a class="navbar-item is-size-5" href="{% url 'signup' %}">
                <p class="">Signup</p>
            </a>
            {% else %}
            <span class="navbar-item is-size-5"><p class="pl-6">Hello, {{request.user}}</p></span>
            <a class="navbar-item is-size-5" href="{% url 'logout' %}">
                <p class="">Logout</p>
            </a>
            {% endif %}
        </div>
    </div>
    </nav>
    <script type="text/javascript">
    (function() {
        var burger = document.querySelector('.burger');
        var nav = document.querySelector('#'+burger.dataset.target);

        burger.addEventListener('click', function() {
            burger.classList.toggle('is-active');
            nav.classList.toggle('is-active');
        });
    })();
    </script>
    <script src="{% static 'pepew/js/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'pepew/css/style.css' %}">
    {% block content %}
    {% endblock %}
    <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <a href="https://www.instagram.com/adamsyauqi/"><img src="https://files.catbox.moe/nckqtf.png" alt="Insta" height="75" width="75"></a>
            <br>
            <h2>Adam Syauqi Medise</h2>
          </p>
        </div>
      </footer>
</body>

pages/templates/photography.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photography</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-parent">
              <article class="tile is-child box">
                <figure class="image is-3by2">
                    <img src="https://files.catbox.moe/um8tj6.jpg" alt="Universal Studio">
                </figure>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <figure class="image is-3by2">
                    <img src="https://files.catbox.moe/u28gyg.jpg" alt="Ameera">
                </figure>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <figure class="image is-3by2">
                    <img src="https://files.catbox.moe/x2c43m.jpg" alt="Kunto Aji">
                </figure>
              </article>
            </div>
          </div>
          <div class="tile is-ancestor">
            <div class="tile is-vertical is-8">
              <div class="tile">
                <div class="tile is-parent is-vertical">
                  <article class="tile is-child box">
                    <figure class="image is-3by2">
                        <img src="https://files.catbox.moe/m4b56u.jpg" alt="Tari Bali">
                    </figure>
                  </article>
                  <article class="tile is-child box">
                    <figure class="image is-3by2">
                        <img src="https://files.catbox.moe/boze6t.jpg" alt="Puti">
                    </figure>
                  </article>
                </div>
                <div class="tile is-parent">
                  <article class="tile is-child box">
                    <figure class="image is-2by3">
                        <img src="https://files.catbox.moe/7gi90e.jpg" alt="Candissa">
                    </figure>
                  </article>
                </div>
              </div>
              <div class="tile is-parent">
                <article class="tile is-child box">
                    <figure class="image is-3by2">
                        <img src="https://files.catbox.moe/dw6vmw.jpg" alt="Dufan">
                    </figure>
                </article>
                <article class="tile is-child box">
                    <figure class="image is-3by2">
                        <img src="https://files.catbox.moe/com563.jpg" alt="Oren Kasur">
                    </figure>
                </article>
              </div>
            </div>
            <div class="tile is-parent is-vertical">
                <article class="tile is-child box">
                    <figure class="image is-2by3">
                        <img src="https://files.catbox.moe/w2jqh4.jpg" alt="Universal Studio Dancer">
                    </figure>
                </article>
                <article class="tile is-child box">
                    <figure class="image is-3by2">
                        <img src="https://files.catbox.moe/iypw6q.jpg" alt="Motor">
                    </figure>
                </article>
            </div>
          </div>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/portfolio.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
        <p class="m-6">
            <div class="columns my-6 py-6">
                <div class="column has-text-centered my-6 py-6">
                    <a class="title has-text-centered" href="{% url 'photography' %}">
                        Photography
                    </a>
                </div>
                <div class="column has-text-centered my-6 py-6">
                    <a class="title has-text-centered" href="{% url 'programming' %}">
                        Programming
                    </a>
                </div>
            </div>   
        </p>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <img src="https://files.catbox.moe/ouyyhl.png" alt="" height="900" width="600" alt="Profile Photo">
            </div>
            <div class="column">
                <h1 class="is-size-1"><p class="mt-6">Adam Syauqi Medise</p></h1>
                <h2 class="is-size-4">Nickname: Auki</h2>
                <h2 class="is-size-4">NPM: 1906292881</h2>
                <br>
                    <p class="my-6">
                        <h3 class="is-size-5">
                            A hardworker, persistent, consistent, photography and music enthusiast, game and cat lover who studies at Computer Science Universitas Indonesia Class of 2019
                        </h3>
                    </p>
                    <br>
                    <p class="m-6">
                    <table class="table is-fullwidth"><caption><h1 class="has-text-weight-bold">Educational Background</h1></caption>
                        <thead>
                            <tr>
                                <th>School</th>
                                <th>Year</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>TK Al-Ikhsan</td>
                                <td>2004-2008</td>
                            </tr>
                            <tr>
                                <td>SDI Tugasku</td>
                                <td>2008-2013</td>
                            </tr>
                            <tr>
                                <td>SMP Labschool Jakarta</td>
                                <td>2013-2016</td>
                            </tr>
                            <tr>
                                <td>SMA Labschool Jakarta</td>
                                <td>2016-2019</td>
                            </tr>
                            <tr>
                                <td>Universitas Indonesia</td>
                                <td>2019-Sekarang</td>
                            </tr>
                        </tbody>
                    </table>
                    </p>
            </div>
        </div>
        <div id="accordion">
            <div class="s_panel">
                 <h3>Current Activity</h3>
                <div class="s_panel_content">I'm currently building my own custom pc now! I'm also studying/learning how to draw using Adobe Photoshop.</div>
            </div>
            <div class="s_panel">
                 <h3>Organizations</h3>
                <div class="s_panel_content">Back in highschool, I was in the Islamic Youth Organization, as a secretary. In University, I'm currently in an Indonesian Minecraft Community Organization named Mineversal. I'm currently in the IT Division, usually handling event-based servers.</div>
            </div>
            <div class="s_panel">
                <h3>Commitee</h3>
               <div class="s_panel_content">In University, I was in the Year Book Documentation Division (it's for orientation). I handled all the pictures needed foe the book like individual photos and group pictures. I also joined the Graduation Commitee, Open House Fasilkom, and Pesta Rakyat Komputer in the Documentation Division too.</div>
           </div>
           <div class="s_panel">
                 <h3>Achievement</h3>
                <div class="s_panel_content">To be honest, not a lot, but back then I was in the karate championship and got I believe 3rd place for my group.</div>
            </div>
        </div>
    </div>
  </section>
  </body>
  {% endblock %}
</html>

pages/templates/testpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Homepage</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  {% extends 'navbarFooter.html' %}
  <body>
    {% block content %}
  <section class="section">
    <div class="container">
      <p class="m-6 p-6">
        <h1 class="title has-text-centered">
          This is a test page!
        </h1>
        <p class="subtitle has-text-centered">
          Click one of these to get started! UwU
        </p>
      </p>
      <p class="m-6 p-6 has-text-centered">
        <a class="button is-outlined is-large" href="{% url 'profile' %}">
          Profile
        </a>
        <a class="button is-outlined is-large" href="{% url 'portfolio' %}">
          Portfolio
        </a>
      </p>
    </div>
  </section>
  </body>
  {% endblock %}
</html>